spring:
  data:
      mongodb:
        authentication-database: admin
        host: localhost
        port: 27017
        database: pruebantt
        username: admin
        password: password
        auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri : http://localhost:8180/auth/realms/PruebaNttRealm
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG