openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Product detail
  license:
    name: MIT
servers:
  - url: http://localhost:8081
paths:
  /product/{productId}:
    get:
      summary: Retrieves product detail
      operationId: getProduct
      tags:
        - product
      parameters:
        - name: productId
          in: path
          required: true
          description: The id of product
          schema:
            type: string
      responses:
        '200':
          description: Product detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        size:
          type: string
        price:
          type: string
        color:
          type: string           
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string